#!/bin/bash

source switchToFinal.sh
# python doCondorThetaTemplates_new.py #Check output dir in doCondorThetaTemplates_new.py inputs in doHists.py_final and analyze.py_final before running!!


#############################
# 
day=2017_9_21  #elMVAfix
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv48sys_elMVAfix_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT400_ST0_mllOS20/ /Shape_accurateLHESys_FRsysSep21_newSigSF_AsymmFRsys
python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv48sys_elMVAfix_AllSys_BB_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT400_ST0_mllOS20/ /Shape_accurateLHESys_FRsysSep21_newSigSF_AsymmFRsys

# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv49sys_elMVAfix_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysSep21_newSigSF_AsymmFRsys
python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv49sys_elMVAfix_AllSys_BB_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysSep21_newSigSF_AsymmFRsys


#############################

# day=2017_8_14  #using minMlllBv4 with FIXED propagated BtagUnc for minMlllB
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv45FRSRHT400low_newRunH_correctedMuTrkSF_fixedMlllBUnc_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT400_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv45FRSRHT400low_newRunH_correctedMuTrkSF_fixedMlllBUnc_AllSys_BB_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT400_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys


#############################

# day=2017_8_10  #using minMlllBv4 with propagated BtagUnc
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv45FRSRHT400low_newRunH_correctedMuTrkSF_addMlllBUnc_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT400_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv45FRSRHT400low_newRunH_correctedMuTrkSF_addMlllBUnc_AllSys_BB_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT400_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys

#############################


# day=2017_7_28  #using minMlllBv4 , and apply 2D lep cut
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv47FRSRHT400low2Dext_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT400_ST0_mllOS20_ptRel10_minDRlJ0p2/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv47FRSRHT400low2Dext_newRunH_newRunH_correctedMuTrkSF_AllSys_BB_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT400_ST0_mllOS20_ptRel10_minDRlJ0p2/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys

#############################

# day=2017_7_24  #using minMlllBv4
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv45FRSRHT400low_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT400_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys

# day=2017_8_8  #using minMlllBv4
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv45FRSRHT400low_newRunH_correctedMuTrkSF_AllSys_BB_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT400_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys

#############################


# day=2017_7_14  #using HTrebinned
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_BB_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys

#############################


# day=2017_7_4  
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv10_FRv42CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv10_FRv42CR2_newRunH_correctedMuTrkSF_AllSys_BB_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys


#############################

# day=2017_4_14  #using FRsys Mar28 for ST0
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_BB_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys
# 
# day=2017_5_15  
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2statOnly_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2Sys2Only_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2Sys4Only_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF_AsymmFRsys

#############################

# day=2017_4_14  
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_BB_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST0_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF

# day=2017_4_13  
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST800_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_BB_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/ /Shape_accurateLHESys_FRsysMar28_newSigSF

# day=2017_4_12 #already including newSignalSF
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2extSys_newRunH_correctedMuTrkSF_AllSys_BB_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/ /Shape_accurateLHESys_FRsysMar28

# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2extSys_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2extSys_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST800_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2extSys_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST900_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2extSys_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1000_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2extSys_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1400_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2extSys_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1500_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2extSys_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1600_mllOS20/ /Shape_accurateLHESys_FRsysMar28

##############################

# day=2017_4_4
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/ /Shape_accurateLHESys_FRsysMar28_extSys DEBUG


# day=2017_4_4 
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST800_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST900_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1000_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1300_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1400_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1500_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1600_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# 
# python doThetaTemplates_1binCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/ /1binCount_accurateLHESys_FRsysMar28
# python doThetaTemplates_1binCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST800_mllOS20/ /1binCount_accurateLHESys_FRsysMar28
# python doThetaTemplates_1binCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1000_mllOS20/ /1binCount_accurateLHESys_FRsysMar28
# 
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST800_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST900_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1000_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1400_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1500_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_correctedMuTrkSF_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1600_mllOS20/ /Shape_accurateLHESys_FRsysMar28


# day=2017_3_28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST800_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST900_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1000_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1300_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1400_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1500_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28
# python doThetaTemplates_4binsCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1600_mllOS20/ /4binsCount_accurateLHEsys_FRsysMar28

# python doThetaTemplates_1binCount_noAnalyze.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/ /1binCount_FRsysMar28
# python doThetaTemplates_1binCount_noAnalyze.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST800_mllOS20/ /1binCount_FRsysMar28

# python doThetaTemplates_1binCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/ /1binCount_accurateLHESys_FRsysMar28
# python doThetaTemplates_1binCount_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST800_mllOS20/ /1binCount_accurateLHESys_FRsysMar28

# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST800_mllOS20/ /Shape_accurateLHESys_FRsysMar28
# python doThetaTemplates_Shape_noAnalyze_accurateLHESys.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv30CR2_newRunH_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1000_mllOS20/ /Shape_accurateLHESys_FRsysMar28

# python doThetaTemplates_4binsCount_noAnalyze.py /user_data/rsyarif/optimization_condor_80x_MultiLep_Full2016_Moriond17_PRv6_FRv18bSys_fixedLumi_ALLsys_step2_addmistag_addMoreSignal_2017_2_17/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/
# python doThetaTemplates_4binsCount_noAnalyze.py /user_data/rsyarif/optimization_condor_80x_MultiLep_Full2016_Moriond17_PRv6_FRv18bSys_fixedLumi_ALLsys_step2_addmistag_addMoreSignal_2017_2_17/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST800_mllOS20/
# python doThetaTemplates_4binsCount_noAnalyze.py /user_data/rsyarif/optimization_condor_80x_MultiLep_Full2016_Moriond17_PRv6_FRv18bSys_fixedLumi_ALLsys_step2_addmistag_addMoreSignal_2017_2_17/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST900_mllOS20/
# python doThetaTemplates_4binsCount_noAnalyze.py /user_data/rsyarif/optimization_condor_80x_MultiLep_Full2016_Moriond17_PRv6_FRv18bSys_fixedLumi_ALLsys_step2_addmistag_addMoreSignal_2017_2_17/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1000_mllOS20/
# python doThetaTemplates_4binsCount_noAnalyze.py /user_data/rsyarif/optimization_condor_80x_MultiLep_Full2016_Moriond17_PRv6_FRv18bSys_fixedLumi_ALLsys_step2_addmistag_addMoreSignal_2017_2_17/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST1100_mllOS20/

#day=2017_3_10
#python doThetaTemplates_4binsCount_noAnalyze.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv24_newFRsys_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/
#python doThetaTemplates_1binCount_noAnalyze.py /user_data/rsyarif/optimization_reMiniAOD_PRv9_FRv24_newFRsys_AllSys_$day/lep1Pt0_jetPt0_MET20_NJets3_NBJets1_HT0_ST700_mllOS20/