#!/bin/bash

# source switchToFinal.sh
# python doCondorKinematics.py

# python doKinematics.py kinematics_condor_ddbkgscan_PRv9_newRunH_elMVAaltFix_FRSRHT400low_2017_9_12
python doKinematics.py kinematics_condor_ddbkgscan_PRv9_newRunH_elMVAaltFix_FRCR2_2017_9_12
# python doKinematics.py kinematics_condor_ddbkgscan_PRv9_newRunH_elMVAaltFix_FRSRHT400_2017_9_13
# python doKinematics.py kinematics_condor_ddbkgscan_PRv9_newRunH_elMVAaltFix_FRSR_2017_9_13
# python doKinematics.py kinematics_condor_ddbkgscan_PRv9_newRunH_elMVAaltFix_FRCR1_2017_9_13
